@startuml ginasio
class Clients {
  - id: Int
  - nome: String
  - locaçao: List<Aluguel>
}

class Aluguel {
  - cliente: Client
  - tempo: Int
  - quadra: Quadra
}

class Quadra {
  - numero: Int
  - aluguel: Aluguel
}

class 
@enduml