@startuml ginasio
class Clients {
  - id: Int
  - nome: String
  - locaçao: List<Aluguel>
}

Clients "1"---*"0..*" Aluguel

class Aluguel {
  - cliente: Client
  - tempo: Int
  - quadra: Quadra
}

Aluguel "o-- Quadra

class Quadra {
  - numero: Int
  - aluguel: Aluguel
  - ginasio: Ginasio
}

Quadra *-- Ginasio

class Ginasio {
  - nome: String
  - quadra: List<Quadra>
}
@enduml