@startuml ginasio
abstract class Pessoa {
  # nome: String
}

Pessoa <| Clients

class Clients {
  - id: Int
  - nome: String
  - locaçao: List<Aluguel>
}

Clients "1" ---* "0..*" Aluguel

class Aluguel {
  - cliente: Client
  - tempo: Int
  - quadra: Quadra
}

Aluguel "1" o--- "1..*" Quadra

class Quadra {
  - numero: Int
  - aluguel: Aluguel
  - ginasio: Ginasio
}

Quadra *-- Ginasio

class Ginasio {
  - nome: String
  - quadra: List<Quadra>
}
@enduml