@startuml teste

scale 1
left to right direction
skinparam PackageStyle rectangle
actor newUser
actor user
rectangle meusys {
  
  newUser -- (register)
  newUser -u-> user
  user -- (login)
  user -- (write)
  user -- (audio)
  user -- (video)
  user -- (photography)
  user -- (attach file)
  user -- (determines)

  (write) -d.> (register item): include
  (audio) -d.> (register item): include
  (video) -d.> (register item): include
  (photography) -d.> (register item): include
  (attach file) -d.> (register item): include

  (determines) -d.> (remove register item): extend
  (determines) -d.> (incubate register item): extend
  (determines) -d.> (reference register item): extend
  (determines) -d.> ( plan action): extend
  (determines) -d.> (delegate): extend

   -d.> (remove register item) (determines): extend
   -d.> (incubate register item) (determines): extend
   -d.> (reference register item) (determines): extend
   -d.> ( plan action) (determines): extend
   -d.> (delegate) (determines): extend
}
@enduml