@startuml teste

scale 1
left to right direction
skinparam PackageStyle rectangle
actor newUser
actor user
rectangle meusys {
  (register item) <. (write)
  
  newUser -- (register)
  user -- (login)
  user -- (write)
  user -- (audio)
  user -- (video)
  user -- (photography)
  user -- (attach file)

}
@enduml