@startuml teste

scale 1
left to right direction
skinparam PackageStyle rect
actor newUser
actor user
rectangle meusys {
  newUser -- (register)
  user -- (login)
  user -- (write)
  user -- (audio)
  user -- (video)
  user -- (photography)
  user -- (attach file)
 (write) .> (register item): includ
 (audio) .> (register item): includ
 (video) .> (register item): includ
 (photography) .> (register item): includ
 (attach file) .> (register item): includ
}
@enduml