@startuml meusys

package Capture <<Rectangle>> {

  ' alguma coisa
  class Something {  
    + id: Int
    
    + created: Date
  }

}

package Capture <<Rectangle>> {

  ' alguma coisa
  class Something {  
    + id: Int
    + created: Date
  }

}

@enduml 