@startuml meusys
start
:make a register;
if (note) then (yes)
  :register;
  stop
elseif (photograph) then (yes)
  :register;
  stop
elseif (audio) then (yes)
  :register;
  stop
elseif (video) then (yes)
  :register;
  stop
elseif (file) then (yes)
  :register;
  stop
else (noting)
  stop
endif
@enduml