@startuml meusys

skinparam ClassAttributeIconSize 0

class signUp {
  - id: Int
  - firstName: String
  - lastName: String
  - userName: String
  - email: String
  - password: String

  + signUp(): void
}

class User {
  - id: Int
  - userName: String
  - password: String

  + logIn(): void
  + signUp(): Int
}

class signIn {
  - userName: String
  - password: String

  + logIn(): void
  + getUserId(): Int
}

@