@startuml meusys

package Capture <<Rectangle>> {

  ' alguma coisa
  class Something {  
    + id: Int
    + what: String
    + created: Date
  }

}

package Explain <<Rectangle>> {

  ' alguma coisa
  class SomethingHasAction< {  
    + id: Int
    + created: Date
  }

}

@enduml 