@startuml meusys
start
:make a record;
if (note) then (yes)
  :register;
  stop
elseif (audio) then (yes)
  :register;
  stop
elseif (audio) then (yes)
  :register;
  stop
elsei (audio) then (yes)
  :register;
  stop
endif
@enduml